"""init

Revision ID: affeb03e06d8
Revises: bcddeac58055
Create Date: 2025-05-27 20:05:34.243187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'affeb03e06d8'
down_revision = 'bcddeac58055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pesanan', sa.Column('kota', sa.Text(), nullable=True))
    op.add_column('pesanan', sa.Column('nomor_handphone', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pesanan', 'nomor_handphone')
    op.drop_column('pesanan', 'kota')
    # ### end Alembic commands ###
