"""init

Revision ID: 657aa18b0087
Revises: 68e95589b452
Create Date: 2025-05-23 23:04:21.496418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657aa18b0087'
down_revision = '68e95589b452'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pesanan', sa.Column('uid_pembeli', sa.Text(), nullable=True))
    op.create_foreign_key(op.f('fk_pesanan_uid_pembeli_pembeli'), 'pesanan', 'pembeli', ['uid_pembeli'], ['uid_pembeli'])
    op.create_foreign_key(op.f('fk_pesanan_id_produk_produk'), 'pesanan', 'produk', ['id_produk'], ['id_produk'])
    op.drop_column('pesanan', 'id_pembeli')
    op.add_column('produk', sa.Column('uid_penjual', sa.Text(), nullable=True))
    op.create_foreign_key(op.f('fk_produk_uid_penjual_penjual'), 'produk', 'penjual', ['uid_penjual'], ['uid_penjual'])
    op.drop_column('produk', 'id_penjual')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produk', sa.Column('id_penjual', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_produk_uid_penjual_penjual'), 'produk', type_='foreignkey')
    op.drop_column('produk', 'uid_penjual')
    op.add_column('pesanan', sa.Column('id_pembeli', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_pesanan_id_produk_produk'), 'pesanan', type_='foreignkey')
    op.drop_constraint(op.f('fk_pesanan_uid_pembeli_pembeli'), 'pesanan', type_='foreignkey')
    op.drop_column('pesanan', 'uid_pembeli')
    # ### end Alembic commands ###
