"""init

Revision ID: 185025ecebc0
Revises: 46a23340b6c2
Create Date: 2025-05-16 22:41:41.036704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185025ecebc0'
down_revision = '46a23340b6c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE pesanan ALTER COLUMN jumlah_pesanan TYPE INTEGER USING jumlah_pesanan::integer;"
    )
    op.execute(
        "ALTER TABLE produk ALTER COLUMN harga_produk TYPE NUMERIC USING harga_produk::numeric;"
    )
    op.execute(
        "ALTER TABLE produk ALTER COLUMN stok_produk TYPE INTEGER USING stok_produk::integer;"
    )

    op.alter_column('pesanan', 'jumlah_pesanan',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint('fk_pesanan_id_produk_produk', 'pesanan', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pesanan_id_produk_produk'), 'pesanan', 'produk', ['id_produk'], ['id_produk'])
    
    op.alter_column('produk', 'harga_produk',
               existing_type=sa.TEXT(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('produk', 'stok_produk',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produk', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('produk', 'stok_produk',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('produk', 'harga_produk',
               existing_type=sa.Numeric(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('produk', 'id_produk')
    op.drop_constraint(op.f('fk_pesanan_id_produk_produk'), 'pesanan', type_='foreignkey')
    op.create_foreign_key('fk_pesanan_id_produk_produk', 'pesanan', 'produk', ['id_produk'], ['id'])
    op.alter_column('pesanan', 'jumlah_pesanan',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
