"""init

Revision ID: 46a23340b6c2
Revises: 0961559f2b89
Create Date: 2025-05-16 22:14:55.994450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a23340b6c2'
down_revision = '0961559f2b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE pesanan ALTER COLUMN id_produk TYPE INTEGER USING id_produk::integer;"
    )
    op.execute(
        "ALTER TABLE pesanan ALTER COLUMN id_pembeli TYPE INTEGER USING id_pembeli::integer;"
    )
    op.execute(
        "ALTER TABLE produk ALTER COLUMN id_penjual TYPE INTEGER USING id_penjual::integer;"
    )
    op.alter_column('pesanan', 'id_produk',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('pesanan', 'id_pembeli',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(op.f('fk_pesanan_id_produk_produk'), 'pesanan', 'produk', ['id_produk'], ['id'])
    op.create_foreign_key(op.f('fk_pesanan_id_pembeli_pembeli'), 'pesanan', 'pembeli', ['id_pembeli'], ['id_pembeli'])
    op.alter_column('produk', 'id_penjual',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_foreign_key(op.f('fk_produk_id_penjual_penjual'), 'produk', 'penjual', ['id_penjual'], ['id_penjual'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_produk_id_penjual_penjual'), 'produk', type_='foreignkey')
    op.alter_column('produk', 'id_penjual',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_pesanan_id_pembeli_pembeli'), 'pesanan', type_='foreignkey')
    op.drop_constraint(op.f('fk_pesanan_id_produk_produk'), 'pesanan', type_='foreignkey')
    op.alter_column('pesanan', 'id_pembeli',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('pesanan', 'id_produk',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
