"""init

Revision ID: 5ebfeae7d060
Revises: e63c10403b70
Create Date: 2025-05-17 10:03:05.051404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ebfeae7d060'
down_revision = 'e63c10403b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foto_produk',
    sa.Column('id_foto_produk', sa.Integer(), nullable=False),
    sa.Column('id_produk', sa.Integer(), nullable=True),
    sa.Column('foto_produk', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_produk'], ['produk.id_produk'], name=op.f('fk_foto_produk_id_produk_produk')),
    sa.PrimaryKeyConstraint('id_foto_produk', name=op.f('pk_foto_produk'))
    )
    op.drop_column('produk', 'foto_produk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produk', sa.Column('foto_produk', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('foto_produk')
    # ### end Alembic commands ###
