"""init

Revision ID: 72ea8fb5ff7c
Revises: d1b86413f32c
Create Date: 2025-05-27 19:28:26.630036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ea8fb5ff7c'
down_revision = 'd1b86413f32c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pesanan', sa.Column('metode_pembayaran', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pesanan', 'metode_pembayaran')
    # ### end Alembic commands ###
