"""init

Revision ID: bcddeac58055
Revises: 72ea8fb5ff7c
Create Date: 2025-05-27 20:03:43.010555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcddeac58055'
down_revision = '72ea8fb5ff7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pesanan', sa.Column('alamat', sa.Text(), nullable=True))
    op.add_column('pesanan', sa.Column('kode_pos', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pesanan', 'kode_pos')
    op.drop_column('pesanan', 'alamat')
    # ### end Alembic commands ###
