"""init

Revision ID: 5886debd5c37
Revises: affeb03e06d8
Create Date: 2025-05-27 20:26:15.769293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5886debd5c37'
down_revision = 'affeb03e06d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
