"""init

Revision ID: af09e9c78f9c
Revises: 0580cc6feb76
Create Date: 2025-05-16 19:37:08.223158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af09e9c78f9c'
down_revision = '0580cc6feb76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penjual',
    sa.Column('id_penjual', sa.Integer(), nullable=False),
    sa.Column('username_penjual', sa.Text(), nullable=True),
    sa.Column('email_penjual', sa.Text(), nullable=True),
    sa.Column('jenis_kelamin', sa.Text(), nullable=True),
    sa.Column('nomor_handphone', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_penjual', name=op.f('pk_penjual'))
    )
    op.create_table('pesanan',
    sa.Column('id_pesanan', sa.Integer(), nullable=False),
    sa.Column('id_produk', sa.Text(), nullable=True),
    sa.Column('id_pembeli', sa.Text(), nullable=True),
    sa.Column('jumlah_pesanan', sa.Text(), nullable=True),
    sa.Column('tanggal_pesanan', sa.Text(), nullable=True),
    sa.Column('status_pesanan', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_pesanan', name=op.f('pk_pesanan'))
    )
    op.create_table('produk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_produk', sa.Text(), nullable=True),
    sa.Column('kategori_produk', sa.Text(), nullable=True),
    sa.Column('deskripsi_produk', sa.Text(), nullable=True),
    sa.Column('merk_produk', sa.Text(), nullable=True),
    sa.Column('harga_produk', sa.Text(), nullable=True),
    sa.Column('stok_produk', sa.Text(), nullable=True),
    sa.Column('foto_produk', sa.Text(), nullable=True),
    sa.Column('id_penjual', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_produk'))
    )
    op.add_column('pembeli', sa.Column('nomor_handphone', sa.Text(), nullable=True))
    op.drop_column('pembeli', 'password_pembeli')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pembeli', sa.Column('password_pembeli', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('pembeli', 'nomor_handphone')
    op.drop_table('produk')
    op.drop_table('pesanan')
    op.drop_table('penjual')
    # ### end Alembic commands ###
