"""init

Revision ID: d1b86413f32c
Revises: cb240df5abf0
Create Date: 2025-05-26 22:42:15.133089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b86413f32c'
down_revision = 'cb240df5abf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_index('my_index', 'models', ['name'], unique=True, mysql_length=255)
    op.drop_constraint('fk_foto_produk_id_produk_produk', 'foto_produk', type_='foreignkey')
    op.create_foreign_key(op.f('fk_foto_produk_id_produk_produk'), 'foto_produk', 'produk', ['id_produk'], ['id_produk'], ondelete='CASCADE')
    op.drop_constraint('fk_pesanan_id_produk_produk', 'pesanan', type_='foreignkey')
    op.drop_constraint('fk_pesanan_uid_pembeli_pembeli', 'pesanan', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pesanan_id_produk_produk'), 'pesanan', 'produk', ['id_produk'], ['id_produk'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_pesanan_uid_pembeli_pembeli'), 'pesanan', 'pembeli', ['uid_pembeli'], ['uid_pembeli'], ondelete='CASCADE')
    op.drop_constraint('fk_produk_uid_penjual_penjual', 'produk', type_='foreignkey')
    op.create_foreign_key(op.f('fk_produk_uid_penjual_penjual'), 'produk', 'penjual', ['uid_penjual'], ['uid_penjual'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_produk_uid_penjual_penjual'), 'produk', type_='foreignkey')
    op.create_foreign_key('fk_produk_uid_penjual_penjual', 'produk', 'penjual', ['uid_penjual'], ['uid_penjual'])
    op.drop_constraint(op.f('fk_pesanan_uid_pembeli_pembeli'), 'pesanan', type_='foreignkey')
    op.drop_constraint(op.f('fk_pesanan_id_produk_produk'), 'pesanan', type_='foreignkey')
    op.create_foreign_key('fk_pesanan_uid_pembeli_pembeli', 'pesanan', 'pembeli', ['uid_pembeli'], ['uid_pembeli'])
    op.create_foreign_key('fk_pesanan_id_produk_produk', 'pesanan', 'produk', ['id_produk'], ['id_produk'])
    op.drop_constraint(op.f('fk_foto_produk_id_produk_produk'), 'foto_produk', type_='foreignkey')
    op.create_foreign_key('fk_foto_produk_id_produk_produk', 'foto_produk', 'produk', ['id_produk'], ['id_produk'])
    op.drop_index('my_index', table_name='models', mysql_length=255)
    op.drop_table('models')
    # ### end Alembic commands ###
