"""init

Revision ID: 0961559f2b89
Revises: af09e9c78f9c
Create Date: 2025-05-16 20:47:58.889370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0961559f2b89'
down_revision = 'af09e9c78f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pembeli', sa.Column('nama_pembeli', sa.Text(), nullable=True))
    op.add_column('penjual', sa.Column('nama_penjual', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('penjual', 'nama_penjual')
    op.drop_column('pembeli', 'nama_pembeli')
    # ### end Alembic commands ###
