"""create Pembeli table

Revision ID: 0580cc6feb76
Revises: 
Create Date: 2025-05-08 20:14:42.291695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0580cc6feb76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models'))
    )
    op.create_index('my_index', 'models', ['name'], unique=True, mysql_length=255)
    op.create_table('pembeli',
    sa.Column('id_pembeli', sa.Integer(), nullable=False),
    sa.Column('username_pembeli', sa.Text(), nullable=True),
    sa.Column('email_pembeli', sa.Text(), nullable=True),
    sa.Column('password_pembeli', sa.Text(), nullable=True),
    sa.Column('jenis_kelamin', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_pembeli', name=op.f('pk_pembeli'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pembeli')
    op.drop_index('my_index', table_name='models', mysql_length=255)
    op.drop_table('models')
    # ### end Alembic commands ###
