"""init

Revision ID: 68e95589b452
Revises: f657a4a119d7
Create Date: 2025-05-23 22:11:58.393661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e95589b452'
down_revision = 'f657a4a119d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pembeli', sa.Column('uid_pembeli', sa.Text(), nullable=True))
    op.add_column('pembeli', sa.Column('role', sa.Text(), nullable=True))
    op.drop_column('pembeli', 'jenis_kelamin')
    op.add_column('penjual', sa.Column('uid_penjual', sa.Text(), nullable=True))
    op.add_column('penjual', sa.Column('role', sa.Text(), nullable=True))
    op.drop_column('penjual', 'jenis_kelamin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('penjual', sa.Column('jenis_kelamin', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('penjual', 'role')
    op.drop_column('penjual', 'uid_penjual')
    op.add_column('pembeli', sa.Column('jenis_kelamin', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('pembeli', 'role')
    op.drop_column('pembeli', 'uid_pembeli')
    # ### end Alembic commands ###
