"""init

Revision ID: 142ea3661c12
Revises: 5886debd5c37
Create Date: 2025-05-31 19:15:38.018519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142ea3661c12'
down_revision = '5886debd5c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pesanan', sa.Column('uid_penjual', sa.Text(), nullable=True))
    op.create_foreign_key(op.f('fk_pesanan_uid_penjual_penjual'), 'pesanan', 'penjual', ['uid_penjual'], ['uid_penjual'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_pesanan_uid_penjual_penjual'), 'pesanan', type_='foreignkey')
    op.drop_column('pesanan', 'uid_penjual')
    # ### end Alembic commands ###
