"""init

Revision ID: cb240df5abf0
Revises: 657aa18b0087
Create Date: 2025-05-25 14:12:52.507727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb240df5abf0'
down_revision = '657aa18b0087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('my_index', table_name='models')
    op.drop_table('models')
    op.add_column('pembeli', sa.Column('gambar_profil', sa.Text(), nullable=True))
    op.add_column('penjual', sa.Column('gambar_profil', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('penjual', 'gambar_profil')
    op.drop_column('pembeli', 'gambar_profil')
    op.create_table('models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_models')
    )
    op.create_index('my_index', 'models', ['name'], unique=True)
    # ### end Alembic commands ###
