"""init

Revision ID: f657a4a119d7
Revises: 5ebfeae7d060
Create Date: 2025-05-18 20:41:02.919266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f657a4a119d7'
down_revision = '5ebfeae7d060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
